Repository Hongik-Graduate-Team/Backend, pull requests merged in 2024-11, with the labels that each got.

#59 fix: 포트폴리오 API Swagger 설명 추가 및 Position 속성 수정 작업
  src/main/java/com/example/Namanba/portfolio/controller/AwardController.java
  src/main/java/com/example/Namanba/portfolio/controller/CareerController.java
  src/main/java/com/example/Namanba/portfolio/controller/CertificationController.java
  src/main/java/com/example/Namanba/portfolio/controller/GPAController.java
  src/main/java/com/example/Namanba/portfolio/controller/LanguageCertController.java
  src/main/java/com/example/Namanba/portfolio/controller/MajorController.java
  src/main/java/com/example/Namanba/portfolio/controller/PortfolioController.java
  src/main/java/com/example/Namanba/portfolio/controller/ResumeController.java
  src/main/java/com/example/Namanba/portfolio/controller/StackController.java
  src/main/java/com/example/Namanba/portfolio/entity/Portfolio.java
  src/main/java/com/example/Namanba/portfolio/entity/Resume.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/Award.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/Career.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/Certification.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/GPA.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/LanguageCert.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/Major.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/Stack.java
Labels: chore, fix

#60 feat: 사용자 시선 평가 로직 구현
  src/main/java/com/example/Namanba/Interview/entity/BasicQuestion.java
  src/main/java/com/example/Namanba/common/constant/StaticValue.java
  src/main/java/com/example/Namanba/common/exception/GlobalErrorCode.java
  src/main/java/com/example/Namanba/evaluation/adaptor/EvaluationContentAdaptor.java
  src/main/java/com/example/Namanba/evaluation/entity/Category.java
  src/main/java/com/example/Namanba/evaluation/entity/CategoryDetails.java
  src/main/java/com/example/Namanba/evaluation/entity/Evaluation.java
  src/main/java/com/example/Namanba/evaluation/entity/EvaluationContent.java
  src/main/java/com/example/Namanba/evaluation/exception/EvaluationErrorCode.java
  src/main/java/com/example/Namanba/evaluation/service/EvaluationDomainService.java
  src/main/java/com/example/Namanba/gaze/controller/GazeController.java
  src/main/java/com/example/Namanba/gaze/dto/request/GazeDataDto.java
  src/main/java/com/example/Namanba/gaze/dto/response/GazeEvaluationDto.java
  src/main/java/com/example/Namanba/gaze/entity/Direction.java
  src/main/java/com/example/Namanba/gaze/entity/enums/GazeDirectionCriteria.java
  src/main/java/com/example/Namanba/gaze/entity/enums/GazeStabilityCriteria.java
  src/main/java/com/example/Namanba/gaze/exception/GazeErrorCode.java
  src/main/java/com/example/Namanba/gaze/usecase/EvaluateGazeUseCase.java
  src/main/java/com/example/Namanba/gaze/usecase/GetGazeEvaluationUseCase.java
  src/main/java/com/example/Namanba/gaze/usecase/processor/GazeEvaluationProcessor.java
  src/main/java/com/example/Namanba/gesture/controller/GestureController.java
  src/main/java/com/example/Namanba/gesture/usecase/processor/GestureEvaluationProcessor.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/Position.java
Labels: refactor, chore, feature

#62 refactor: 사용자 시선 평가 로직 리팩토링
  src/main/java/com/example/Namanba/evaluation/repository/EvaluationRepository.java
  src/main/java/com/example/Namanba/gaze/dto/request/GazeDataDto.java
  src/main/java/com/example/Namanba/gaze/entity/DirectionCounts.java
  src/main/java/com/example/Namanba/gaze/usecase/processor/GazeEvaluationProcessor.java
Labels: refactor, fix

#65 refactor: 사용자 시선 및 자세 평가 메시지 구조 개선
  src/main/java/com/example/Namanba/gaze/dto/response/GazeEvaluationDto.java
  src/main/java/com/example/Namanba/gaze/usecase/processor/GazeEvaluationProcessor.java
  src/main/java/com/example/Namanba/gesture/usecase/processor/GestureEvaluationProcessor.java
Labels: refactor

#73 refactor: 제스처 평가 기준 변경 (#72)
  src/main/java/com/example/Namanba/Interview/entity/CustomQuestion.java
  src/main/java/com/example/Namanba/evaluation/entity/Evaluation.java
  src/main/java/com/example/Namanba/gesture/dto/request/GestureDataDto.java
  src/main/java/com/example/Namanba/gesture/entity/GestureCriteria.java
  src/main/java/com/example/Namanba/gesture/usecase/processor/GestureEvaluationProcessor.java
  src/main/java/com/example/Namanba/portfolio/entity/Portfolio.java
Labels: refactor

#74 feat: 마이페이지 인터뷰 목록 페이징 및 상세 데이터 API 구현
  src/main/java/com/example/Namanba/Interview/adaptor/InterviewAdaptor.java
  src/main/java/com/example/Namanba/Interview/controller/InterviewController.java
  src/main/java/com/example/Namanba/Interview/controller/InterviewReportController.java
  src/main/java/com/example/Namanba/Interview/converter/InterviewConverter.java
  src/main/java/com/example/Namanba/Interview/dto/CustomQuestionsDto.java
  src/main/java/com/example/Namanba/Interview/dto/request/InterviewPageRequest.java
  src/main/java/com/example/Namanba/Interview/dto/response/InterviewDto.java
  src/main/java/com/example/Namanba/Interview/dto/response/InterviewListResponse.java
  src/main/java/com/example/Namanba/Interview/dto/response/InterviewReportResponse.java
  src/main/java/com/example/Namanba/Interview/entity/EvaluationStatus.java
  src/main/java/com/example/Namanba/Interview/entity/Interview.java
  src/main/java/com/example/Namanba/Interview/exception/InterviewErrorCode.java
  src/main/java/com/example/Namanba/Interview/repository/InterviewRepository.java
  src/main/java/com/example/Namanba/Interview/service/InterviewService.java
  src/main/java/com/example/Namanba/Interview/usecase/ReadInterviewListUseCase.java
  src/main/java/com/example/Namanba/Interview/usecase/ReadInterviewReportUseCase.java
  src/main/java/com/example/Namanba/evaluation/adaptor/EvaluationAdaptor.java
  src/main/java/com/example/Namanba/evaluation/entity/Evaluation.java
  src/main/java/com/example/Namanba/portfolio/entity/Portfolio.java
  src/main/java/com/example/Namanba/portfolio/entity/Resume.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/Award.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/Career.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/Certification.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/GPA.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/LanguageCert.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/Major.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/Position.java
  src/main/java/com/example/Namanba/portfolio/entity/subitems/Stack.java
Labels: refactor, ✨feature

#77 fix: 페이지네이션 수정 및 gesture 수정
  src/main/java/com/example/Namanba/Interview/adaptor/InterviewAdaptor.java
  src/main/java/com/example/Namanba/Interview/usecase/ReadInterviewReportUseCase.java
  src/main/java/com/example/Namanba/evaluation/entity/CategoryDetails.java
  src/main/java/com/example/Namanba/evaluation/service/EvaluationDomainService.java
  src/main/java/com/example/Namanba/gesture/usecase/processor/GestureEvaluationProcessor.java
Labels: ✨feature, fix

#87 refactor: 코드 스타일 통일 및 스웨거 설명 추가
  src/main/java/com/example/Namanba/user/controller/OauthController.java
Labels: ♻️ refactor
